"""The only business tools available to the StreamSphere agent."""

from urllib.parse import urlsplit

import requests
from fastapi import HTTPException

from app.config import settings


def require_configuration():
    url = urlsplit(settings.STREAMING_BASE_URL)
    local_http = url.scheme == "http" and url.hostname in ("localhost", "127.0.0.1", "::1")
    if (
        not url.hostname
        or (url.scheme != "https" and not local_http)
        or url.username or url.password or url.query or url.fragment
        or url.path not in ("", "/")
        or len(settings.STREAMING_API_KEY) < 32
        or len(settings.STREAMING_TOOL_API_KEY) < 32
        or not 0 < settings.STREAMING_TOOL_TIMEOUT <= 30
    ):
        raise HTTPException(503, "Configure the StreamSphere URL and backend service keys.")
    if settings.USE_AWS and not settings.USE_RDS:
        raise HTTPException(503, "StreamSphere requires SQLite or RDS conversation and consent storage.")


def _call(method, path, **kwargs):
    require_configuration()
    try:
        response = requests.request(
            method,
            settings.STREAMING_BASE_URL.rstrip("/") + path,
            headers={"Authorization": f"Bearer {settings.STREAMING_TOOL_API_KEY}", "Accept": "application/json"},
            timeout=settings.STREAMING_TOOL_TIMEOUT,
            allow_redirects=False,
            **kwargs,
        )
    except requests.Timeout:
        raise HTTPException(504, "StreamSphere did not respond. Refresh your account before retrying.") from None
    except requests.RequestException:
        raise HTTPException(502, "The StreamSphere business service is unavailable.") from None
    if response.status_code == 409:
        raise HTTPException(409, "The confirmation expired or the membership changed. Refresh and request a new confirmation.")
    if not 200 <= response.status_code < 300:
        raise HTTPException(502, "The StreamSphere business tool could not complete this request.")
    try:
        result = response.json()
    except ValueError:
        raise HTTPException(502, "StreamSphere returned an invalid business tool response.") from None
    if not isinstance(result, dict) or result.get("error") or result.get("ok") is False:
        raise HTTPException(502, "StreamSphere returned an invalid business tool response.")
    return result


def get_account(user_id):
    # Identity is supplied by the authenticated backend, never generated by the model.
    result = _call("GET", "/api/tools/account", params={"user_id": user_id})
    account, policy = result.get("account"), result.get("policy")
    if (
        not isinstance(account, dict) or not isinstance(policy, dict)
        or account.get("subscription_status") not in ("active", "cancelled")
        or type(policy.get("same_day_refund_eligible")) is not bool
        or type(policy.get("refund_amount_cents")) is not int
        or not 0 <= policy["refund_amount_cents"] <= 9007199254740991
        or policy.get("currency") != "USD"
        or policy.get("refund_destination") != "demo_wallet"
        or policy.get("access_ends") != "immediately"
        or policy.get("user_consent_required") is not True
    ):
        raise HTTPException(502, "StreamSphere returned invalid account or refund policy data.")
    return result


def cancel_subscription(consent_id):
    # StreamSphere resolves account, amount and approval atomically from this ID.
    result = _call("POST", "/api/tools/cancel-subscription", json={"consent_id": consent_id})
    account = result.get("account")
    amount = result.get("refund_amount_cents")
    if (
        not isinstance(account, dict)
        or not (account.get("subscription_status") == "cancelled"
                or (account.get("subscription_status") == "active" and result.get("already_executed") is True))
        or type(amount) is not int or not 0 <= amount <= 9007199254740991
    ):
        raise HTTPException(502, "Cancellation could not be verified. Refresh your membership before retrying.")
    return result
